name: Bug report
description: Report a bug in platform or service
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear and concise bug description.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps and expected vs actual behavior.
    validations:
      required: true
